Repository schneiderkamplab/synthesizers, pull requests merged in 2024-08, with the labels that each got.

#13 docstring added to pipeline
  synthesizers/pipelines/__init__.py
Labels: documentation

#14 Added keyword arguments to synthcity adapter.
  .gitignore
  examples/tutorial1_local_data.ipynb
  examples/tutorial2_multiple_methods.ipynb
  synthesizers/adapters/synthcity.py
Labels: enhancement

#15 Fixed train_adapter parameter for Synthesize
  README.md
  synthesizers/pipelines/tabular_synthesis.py
Labels: bug
